app:
  name: 'p2p-proccessing'
  version: '1.0.0'

port: ':3000'

logger:
  log_level: 'debug'
  rollbar_env: '.env'

postgres:
  pool_max: 2
  url: 'postgres://jonnytomato@localhost:5432/c2c?sslmode=disable'