app:
  name: 'p2p-proccessing'
  version: '1.0.0'

port: ':8080'

logger:
  log_level: 'debug'
  rollbar_env: '.env'

postgres:
  pool_max: 2
  url: 'postgres://jonnytomato:flints1488@ec2-44-211-220-125.compute-1.amazonaws.com:5432/c2c?sslmode=disable'